// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMB.Repository.Domain;

namespace PMB.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220714073437_mig2")]
    partial class mig2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PMB.Repository.Domain.TblPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AvvalMoney")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreteDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Ex4Ir")
                        .HasColumnType("float");

                    b.Property<double>("HdPay")
                        .HasColumnType("float");

                    b.Property<double>("IraniCard")
                        .HasColumnType("float");

                    b.Property<double>("Nobitex")
                        .HasColumnType("float");

                    b.Property<double>("Payfa24")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TblPriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
