// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMB.Repository.Domain;

namespace PMB.Repository.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PMB.Repository.Domain.TblError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Line")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TblErrors");
                });

            modelBuilder.Entity("PMB.Repository.Domain.TblPriceHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AvvalMoneyBuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("AvvalMoneySellPrice")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreteDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Ex4IrBuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("Ex4IrSellPrice")
                        .HasColumnType("float");

                    b.Property<double>("HdPayBuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("HdPaySellPrice")
                        .HasColumnType("float");

                    b.Property<double>("IraniCardBuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("IraniCardSellPrice")
                        .HasColumnType("float");

                    b.Property<double>("NobitexBuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("NobitexSellPrice")
                        .HasColumnType("float");

                    b.Property<double>("Payfa24BuyPrice")
                        .HasColumnType("float");

                    b.Property<double>("Payfa24SellPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("TblPriceHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
